#!/bin/sh

# Package
PACKAGE="ow2mqtt"
DNAME="ow2mqtt"
#WDIR=/var/services/web/$PACKAGE

# Others

preinst ()
{
    #mkdir -p ${WDIR}
    mkdir -p /mnt/data
    exit 0
}

postinst ()
{
    chown -R ${USER}:root ${SYNOPKG_PKGDEST}
    exit 0
}

preuninst ()
{
    #umount $WDIR
    #rm -rf $WDIR
    exit 0
}

postuninst ()
{
    exit 0
}

preupgrade ()
{
    exit 0
}

postupgrade ()
{
    exit 0
}
